{
  # The name of your desired mods on Modrinth separated by ','.
  "mods": [
    "sodium"
  ],
  # The versions of minecraft for which you want to download the mods. Use "NEWEST" for the newest (full) version
  "versions": [
    "1.21", "1.18", "NEWEST"
  ],
  # Where the mods will be saved, separated into version folders. Use 'CURRENT' for current folder.
  "path": 'CURRENT/mods'
}